"""Export meeting notes to formatted markdown."""

from jinja2 import Template
from datetime import datetime


TEMPLATE = """# Meeting Notes - {{ date }}

{{ summary }}

---

{{ action_items }}

---

*Generated by meeting-notes-ai*
"""


class MarkdownExporter:
    def __init__(self):
        self.template = Template(TEMPLATE)

    def export(self, summary: str, action_items: str, output_path: str):
        content = self.template.render(
            date=datetime.now().strftime("%Y-%m-%d"),
            summary=summary,
            action_items=action_items,
        )
        with open(output_path, "w") as f:
            f.write(content)
        return output_path
